static_obj_x = 90;
static_obj_y = 0;
[match_point_index, proj_x, proj_y, proj_heading, proj_kappa] = matchpoint(...
            static_obj_x ,static_obj_y ,...
            plan_referenceline_x, plan_referenceline_y, plan_referenceline_heading, plan_referenceline_kappa);
[static_obj_s,static_obj_l] = Cartesian2Frenet_sl(static_obj_x, static_obj_y,...
                plan_referenceline_x,plan_referenceline_y,...
                proj_x,proj_y,proj_heading,match_point_index,plan_referenceline_s);